# Generated by Django 4.2.6 on 2023-10-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marshall', '0002_students_teacher_alter_attendance_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='students',
            name='teacher',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
